import NextAuthProvider from "@/providers/NextAuthProvider";
import "./globals.css";
import NavBar from "@/components/NavBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
      
        className={` antialiased w-7xl mx-auto  min-h-screen`}
      >
        <NextAuthProvider>
          <NavBar/>
        {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
